[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "A library to model the Coinche card game."
documentation = "http://gyscos.github.io/libcoinche/libcoinche/index.html"
keywords = ["coinche", "game", "cards"]
license = "MIT"
name = "libcoinche"
readme = "Readme.md"
repository = "https://github.com/Gyscos/libcoinche"
version = "0.1.9"

[dependencies]
clippy = { version = "0.0.44", optional = true }
rand = "0.3"
rustc-serialize = "0.3"

[features]
default = []
